# Generated by Django 2.1 on 2018-10-11 14:19

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20181010_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 11, 14, 19, 31, 628138, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(default='../img/controller.jpg', upload_to='uploads/'),
        ),
    ]
